name: Build iOS app

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    env:
      APP_ID: es.juntadeandalucia.noticiasandalucia
      PROJECT_WORKSPACE: Portavoz.xcworkspace
      APP_NAME: Portavoz
      PROJECT_SCHEME: PortavozPRO
      PROJECT_CONFIGURATION: PortavozPRO
      UUID_PROVISION: bece3ee8-b1c4-42ec-abbc-6f28c0fc961d
      DEVELOPMENT_TEAM: 2P43RZUB7Q

    steps:
      - uses: actions/checkout@v2.1.0
      - name: Get source from external repo
        run: git clone https://${{ secrets.REPO_USER }}:${{ secrets.REPO_PASS }}@gitlab.juntadeandalucia.es/noticias-portavoz/ios-app-noticias-portavoz.git source --depth 1
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.2.1.app
      - name: Setup cert
        run: ./.github/secrets/decrypt_certs.sh
        env:
          IOS_CERTIFICATE_PASS: ${{ secrets.IOS_CERTIFICATE_PASS }}
          ENCRYPT_PASS: ${{ secrets.ENCRYPT_PASS }}
      - name: Fix manual sign pods
        run: |
          mkdir logs
          echo "post_install do |installer| 
          installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
          config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = \"\"
          config.build_settings['CODE_SIGNING_REQUIRED'] = \"NO\"
          config.build_settings['CODE_SIGNING_ALLOWED'] = \"NO\"
          end
          end
          end" >> Podfile
        working-directory: source
      - name: Pods Install
        id: pods_install
        run: pod install > logs/pod_install.log
        working-directory: source
      - name: Build app
        id: xcodebuild_export
        run: |
          xcodebuild archive \
           -workspace "$PROJECT_WORKSPACE" \
           -scheme "$PROJECT_SCHEME" \
           -sdk iphoneos13.2 \
           -configuration "$PROJECT_CONFIGURATION" \
           -archivePath $PWD/build/app_build.xcarchive \
           CODE_SIGN_IDENTITY="Apple Distribution" \
           DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
           PROVISIONING_PROFILE="$UUID_PROVISION" \
           CODE_SIGN_STYLE="Manual" > logs/xcodebuild_archive.log
        working-directory: source
      - name: Create ExportOptions
        run: create_export.sh
      - name: Export IPA
        id: xcodebuild_archive
        run: |
          xcodebuild -exportArchive \
          -exportPath $PWD/build \
          -archivePath $PWD/build/app_build.xcarchive \
          -exportOptionsPlist $PWD/ExportOptions.plist > logs/xcodebuild_export.log
        working-directory: source
      - name: Upload build to action
        uses: actions/upload-artifact@v1
        with:
          name: 'app_build' #not accepts env variable i.e. $APP_NAME
          path: './source/build/'
      - name: Upload logs to action
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: './source/logs/'
      - name: Create zip logs
        if: failure()
        run: zip logs.zip -r logs
        working-directory: source
      - name: Send email
        if: failure()
        uses: dawidd6/action-send-mail@v2.2.0        
        with:
          # SMTP server address
          server_address: mail.juntadeandalucia.es
          # SMTP server port
          server_port: 465
          # Authenticate as this user to SMTP server
          username: aplicaciones.moviles
          # Authenticate with this password to SMTP server
          password: ${{ secrets.EMAIL_PASS }}
          # Subject of mail message
          subject: "[SIGC][IOS][CD/CI] ${{env.APP_NAME}}(${{env.APP_ID}})"
          # Body of mail message (might be a filename prefixed with file:// to read from)
          body: "PODS_INSTALL: ${{steps.pods_install.outcome}}\nEXPORT PROCCESS: ${{steps.xcodebuild_export.outcome}}\nARCHIVE PROCESS: ${{steps.xcodebuild_archive.outcome}}\nPUBLISH APP: TODO"
          # Recipients mail addresses (separated with comma)
          to: jgleal@minsait.com,fborja.manas@juntadeandalucia.es
          # Full name of mail sender (might be with an email address specified in <>)
          from: ${{env.APP_NAME}} <aplicaciones.moviles@juntadeandalucia.es>
          # Content-Type HTTP header (text/html or text/plain)
          #content_type: # optional, default is text/plain
          # Files that will be added to mail message attachments (separated with comma)
          attachments: ./source/logs.zip
        
       #      - name: Publish ipa to iTunes Connect
#        run: xcrun altool --upload-app --type ios \
#              --file "app/platforms/ios/build/$APP_NAME.ipa"
#  --username "${APPLE_ID_USER}" --password "${APPLE_ID_PASS}"
#        env:
#           APPLE_ID_USER: ${{ secrets.APPLE_USER }}
#           APPLE_ID_PASS: ${{ secrets.APPLE_PASS }}
