name: Build iOS app

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    env:
      APP_ID: es.juntadeandalucia.noticiasandalucia
      APP_NAME: Portavoz
      PROJECT_WORKSPACE: Portavoz.xcworkspace      
      PROJECT_SCHEME: PortavozPRO
      PROJECT_CONFIGURATION: PortavozPRO
      CODE_SIGN_IDENTITY: iPhone Distribution
      UUID_PROVISION: bece3ee8-b1c4-42ec-abbc-6f28c0fc961d
      DEVELOPMENT_TEAM: 2P43RZUB7Q

    steps:
      - uses: actions/checkout@v2.1.0
      - name: Get source from external repo
        run: git clone https://oauth2:${{secrets.GITLAB_TOKEN}}@gitlab.juntadeandalucia.es/noticias-portavoz/ios-app-noticias-portavoz.git source --depth 1
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.2.1.app
      - name: Setup cert
        run: ./.github/secrets/decrypt_certs.sh
        env:
          IOS_CERTIFICATE_PASS: ${{ secrets.IOS_CERTIFICATE_PASS }}
          ENCRYPT_PASS: ${{ secrets.ENCRYPT_PASS }}
      - name: Fix manual sign pods
        run: |
          mkdir logs
          echo "post_install do |installer| 
          installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
          config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = \"\"
          config.build_settings['CODE_SIGNING_REQUIRED'] = \"NO\"
          config.build_settings['CODE_SIGNING_ALLOWED'] = \"NO\"
          end
          end
          end" >> Podfile
        working-directory: source
      - name: Pods Install
        id: pods_install
        run: pod install > logs/pod_install.log
        working-directory: source
      - name: Build app
        id: xcodebuild_export
        run: |
          xcodebuild archive \
           -workspace "$PROJECT_WORKSPACE" \
           -scheme "$PROJECT_SCHEME" \
           -configuration "$PROJECT_CONFIGURATION" \
           -archivePath $PWD/build/app_build.xcarchive \
           CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
           DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
           PROVISIONING_PROFILE="$UUID_PROVISION" \
           CODE_SIGN_STYLE="Manual" > logs/xcodebuild_archive.log
#          -sdk iphoneos13.2 \
#          IPHONEOS_DEPLOYMENT_TARGET=10.0 \
        working-directory: source
      - name: Create ExportOptions
        run: create_export.sh
      - name: Export IPA
        id: xcodebuild_archive
        run: |
          xcodebuild -exportArchive \
          -exportPath $PWD/build \
          -archivePath $PWD/build/app_build.xcarchive \
          -exportOptionsPlist $PWD/ExportOptions.plist > logs/xcodebuild_export.log
        working-directory: source       
#      - name: Publish ipa to iTunes Connect
#        id: publish_ipa
#        run: xcrun altool --upload-app --type ios \
#              --file "$PWD/build/app_build.ipa" \
#              --username "${{secrets.APPLE_USER}}" --password "${{secrets.APPLE_PASS}}" > logs/publish_ipa.log
#        working-directory: source  
      - name: Create zip logs        
        run: zip logs.zip -r logs
        working-directory: source
      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v2.2.0        
        with:
          server_address: mail.juntadeandalucia.es
          server_port: 465
          username: aplicaciones.moviles
          password: ${{ secrets.EMAIL_PASS }}
          subject: "[SIGC][IOS][CD/CI] ${{env.APP_NAME}}(${{env.APP_ID}})"
          # Body of mail message (might be a filename prefixed with file:// to read from)
          body: "PODS_INSTALL: ${{steps.pods_install.outcome}}\nEXPORT PROCCESS: ${{steps.xcodebuild_export.outcome}}\nARCHIVE PROCESS: ${{steps.xcodebuild_archive.outcome}}\nPUBLISH APP: ${{steps.publish_ipa.outcome}}"
          to: jgleal@minsait.com,fborja.manas@juntadeandalucia.es
          from: ${{env.APP_NAME}} <aplicaciones.moviles@juntadeandalucia.es>
          # Content-Type HTTP header (text/html or text/plain)
          #content_type: # optional, default is text/plain
          # Files that will be added to mail message attachments (separated with comma)
          attachments: ./source/logs.zip
  
####################################### FAILURE SECTION ##############################################
      - name: Upload logs to action
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.APP_NAME}}_logs
          path: './source/logs/'      
      - name: Upload build to action
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.APP_NAME}}_build
          path: './source/build/'       
